server:
  port: 5000

spring:
  rabbitmq:
    addresses: localhost

  data:
    elasticsearch:
      host: localhost
      ## to fill if authentication is needed
      # user:
      # password:

powsybl-ws:
  database:
    host: localhost
