spring:
  application:
    name: case-server

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
      output-bindings: publishCaseImport

powsybl-ws:
  database:
    name: case_metadata